---
    name: 'Test docker install on macos-13-x86_64'
    
    on:
      push:
    
    permissions: # least privileges, see https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions
      contents: read
    
    jobs:
      docker:
        name: docker
        runs-on: macos-13
        steps:
          - run: sysctl kern.hv_support
          - run: brew install colima docker
          - run: colima start
          - run: docker ps
          - run: docker pull alpine:latest
          - run: docker image ls
